[theme]
base = "light"
primaryColor = "#2a78d6"
backgroundColor = "#f6f7f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0b0b0b"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
